version: '3'
services:
  backend:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn --config gunicorn_config.py myproject.wsgi:application"
    restart: always
    expose:
      - "8000"
    volumes:
      - ./:/app

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./static:/var/www/static  # Ensure static files are served correctly
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - backend

